name: Run Unit tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  check_run:
#     types: [created, rerequested, requested_action]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_unit_tests:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Python Pytest Github Action
      uses: fylein/python-pytest-github-action@v2
